### ISSUE TITLE
Flycheck reports: No checker 

### ISSUE THREAD

**Issue by dnadales** [emacs-languagetool/flycheck-languagetool#15]
Thanks for putting this package together :pray: 

After I configured Emacs according to the instructions given in the README, I opened a text file, and ran `flycheck-mode`. After doing this, Flycheck reports: no checker. Am I missing something?

**Comment by dnadales** [comment]
Nevermind. The path I specified was wrong. It seems `flycheck-languagetool` died silently.

**Comment by titanofold** [comment]
I've run into this error as well: Silent failure from both Flycheck and flycheck-languagetool.

`flycheck-verify-setup` pointed out the error to me.
