### ISSUE TITLE
mu4e: row and column numbers of errors displayed are wrong

### ISSUE THREAD

**Issue by rdiaz02** [emacs-languagetool/flycheck-languagetool#16]
Same issue (regarding wrong column and row numbers) as in https://github.com/emacs-grammarly/flycheck-grammarly/issues/13. This also happens with flymake-languagetool. 

This is a screenshot:

![flt](https://user-images.githubusercontent.com/1688611/147755527-ae0a9cd0-dc22-45e9-9203-d5d93910803d.png)

**Comment by mavit** [comment]
I don't use `mu4e`, but I wonder if this is related to text properties, in which case #19 might help.  Could you try it?

**Comment by kennyballou** [comment]
Can confirm this does not appear to be an issue anymore.

![Screenshot from 2022-11-10 10-38-23](https://user-images.githubusercontent.com/2186188/201167358-2065b104-6e8a-4053-bb32-9aeeca1eb2cd.png)
