### ISSUE TITLE
Failed to define function flycheck-languagetool-steup

### ISSUE THREAD

**Issue by titanofold** [emacs-languagetool/flycheck-languagetool#24]
I get either this error:

    File mode specification error: (error Autoloading file /home/titan/.emacs.d/elpa/flycheck-languagetool-20220731.2301/flycheck-languagetool.elc failed to define function flycheck-languagetool-steup)

Or I get the following error:

    run-hooks: Autoloading file /home/titan/.emacs.d/elpa/flycheck-languagetool-20220731.2301/flycheck-languagetool.elc failed to define function flycheck-languagetool-steup

I'm not terribly elisp savvy, this is the extent of my config with flycheck-languagetool:

```elisp
  (use-package flycheck-languagetool
    :after (flycheck langtool langtool-ignore-fonts)
    :custom (flycheck-languagetool-url "localhost")
    :hook ((text-mode LaTeX-mode markdown-mode) . flycheck-languagetool-steup))
```

If I try to invoke the function manually, it doesn't seem to do anything. I mostly work in LaTeX where I'd want grammar checking, and I wonder if LSP is overriding that.

If I call languagetool from the langtool package, it works as expected.

**Comment by jcs090218** [comment]
The error seems to be an issue from `package.el` and not specific to this package. Are you upgrading this package but failed to remove the old one [1]? Are you using a different version of Emacs [2]?

1. [How to solve "Autoloading failed to define function sml-mode"?](https://emacs.stackexchange.com/questions/30898/how-to-solve-autoloading-failed-to-define-function-sml-mode)
2. [Failed to define function w/ .elc files?](https://www.reddit.com/r/emacs/comments/q7fjbi/comment/hgiii3k/?utm_source=share&utm_medium=web2x&context=3)

Try reinstall this package, so you get the clean byte-compile result.

**Comment by jcubic** [comment]
this is old, but it seems no one noticed a typo in name `flycheck-languagetool-steup` it should be `setup`.

**Comment by titanofold** [comment]
> this is old, but it seems no one noticed a typo in name `flycheck-languagetool-steup` it should be `setup`.

That's definitely what it was!
