### ISSUE TITLE
unable to use system languagetool service

### ISSUE THREAD

**Issue by fedeinthemix** [emacs-languagetool/flycheck-languagetool#26]
I'm running a system providing a languatetool service. It's available at `http://localhost:8081/v2/check`. I've tried setting `flycheck-languagetool-url`, but it doesn't work. What's the proper way to use it instead of starting a new process?

**Comment by mavit** [comment]
In what way does it not work?  Do you get an error message?

What did you set `flycheck-languagetool-url` to?  Try `http://localhost:8081`.

**Comment by fedeinthemix** [comment]
I stupidly set `flycheck-languagetool-url` to `http://localhost:8081/v2/check`. Setting it to `http://localhost:8081` it does work.
Thanks for the prompt reply!
