### ISSUE TITLE
Where should I place the Premium LT credentials? 

### ISSUE THREAD

**Issue by maikol-solis** [emacs-languagetool/flycheck-languagetool#32]
Hi, 

I have a Premium LT account and I want to use those with `flycheck`. I noticed that `flymake-languagetool` has these options. 

Thanks for the help.

**Comment by mavit** [comment]
Try adding `username` and `apiKey` parameters to `flycheck-languagetool-check-params`.

**Comment by maikol-solis** [comment]
Hi @mavit 

I am sorry, but your answer is unclear to me. 

How should put those parameters, as list? There is no help on the README for setting them up. 

Thanks for the help.

**Comment by mavit** [comment]
Customization `flycheck-languagetool-check-params` is a list of parameter name-value pairs that we pass through to the LanguageTool server.

See https://www.gnu.org/software/emacs/manual/html_node/emacs/Easy-Customization.html for a general explanation of Emacs' customization feature, and https://languagetool.org/http-api/swagger-ui/#!/default/post_check for a list of parameters that the LanguageTool server will accept.

Also, I have released a new version of this package which hopefully makes this process a bit more obvious.
